import os
import sys

"""
The Context Consolidator (The "ReConstructor")

Purpose:
This script builds the "Boot Disk" for your AI. It reads the list of files
generated by `list_project_tree.py` and combines their contents into a single
Markdown file (`RECONSTRUCTOR_CONTEXT.md`).

Why do we need this?
AI Context Windows are limited. Pasting files one by one is slow and error-prone.
This script formats everything into a standardized block that the AI can ingest
instantly to understand the entire project state.

Usage:
python tools/serializer.py
"""

def get_project_name_from_repo_root(repo_root_path):
    """
    Attempts to guess the project name from the folder name.
    Used for the file headers.
    """
    try:
        project_name = os.path.basename(repo_root_path)
        if project_name:
            return project_name
    except Exception:
        pass
    return "AI-Assisted-Student-Project"

def create_consolidated_context(file_list_path, output_file_path):
    """
    Reads a list of files and consolidates them into a single Markdown file
    with headers/footers for AI ingestion.
    """
    print(f"Starting ReConstructor context consolidation...")
    print(f"Reading file list from: {file_list_path}")

    file_paths = []
    encodings_to_try = ['utf-8', 'utf-16', 'cp1252']
    
    file_list_read_success = False
    for encoding in encodings_to_try:
        try:
            with open(file_list_path, 'r', encoding=encoding) as f:
                file_paths = [line.strip() for line in f if line.strip() and not line.strip().startswith('#')]
            file_list_read_success = True
            break
        except UnicodeDecodeError:
            continue
        except FileNotFoundError:
            print(f"CRITICAL ERROR: Could not find file list '{file_list_path}'")
            print("Did you run 'list_project_tree.py' first?")
            return

    if not file_list_read_success:
        print(f"ERROR: Could not decode {file_list_path} with any of {encodings_to_try}.")
        return

    if not file_paths:
        print("ERROR: No file paths found in the list.")
        return

    repo_root = os.getcwd()
    project_name = get_project_name_from_repo_root(repo_root)

    try:
        with open(output_file_path, 'w', encoding='utf-8') as outfile:
            for file_path in file_paths:
                full_file_path = os.path.join(repo_root, file_path)
                
                header_path = file_path.replace(os.sep, '/')
                if not header_path.startswith('/'):
                    header_path = '/' + header_path

                try:
                    # Try reading file content with multiple encodings
                    content = ""
                    read_success = False
                    for enc in ['utf-8', 'utf-16', 'cp1252']:
                        try:
                            with open(full_file_path, 'r', encoding=enc) as infile:
                                content = infile.read()
                            read_success = True
                            break
                        except UnicodeDecodeError:
                            continue
                    
                    if not read_success:
                         print(f"WARNING: Skipping {file_path} (Encoding error)")
                         continue

                    outfile.write(f"# Project: {project_name}; File: {header_path}\n\n")
                    outfile.write(content)
                    outfile.write(f"\n\n---[ END OF FILE: {header_path} ]---\n\n")
                    
                    print(f"Processed: {file_path}")

                except FileNotFoundError:
                    print(f"WARNING: File listed in text file but not found on disk: {file_path}")
                except Exception as e:
                    print(f"ERROR processing file {file_path}: {e}")

        print(f"\nSuccess! Context created at: {output_file_path}")
        print("You can now copy the content of this file and paste it to your AI.")

    except Exception as e:
        print(f"ERROR writing output file: {e}")

if __name__ == "__main__":
    FILE_LIST = 'reconstructor-file-list.txt'
    OUTPUT_FILE = 'RECONSTRUCTOR_CONTEXT.md'
    
    if len(sys.argv) > 1:
        FILE_LIST = sys.argv[1]

    create_consolidated_context(FILE_LIST, OUTPUT_FILE)
    